##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.19.2] date: [Fri Apr 21 12:24:30 CST 2023] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = F411-FlightController


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32f4xx_it.c \
Core/Src/syscalls.c \
Core/Src/Dshot.c \
Core/Src/Dshot_tim.c \
Core/Src/rx/crsf.c \
Core/Src/driver/iic.c \
Core/Src/driver/system.c \
Core/Src/driver/uart.c \
Core/Src/common/crc.c \
Core/Src/streambuf.c \
Core/Src/stm32f4xx_hal_timebase_tim.c \
Core/Src/freertos.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
Core/Src/system_stm32f4xx.c \
Middlewares/MPU6050_Motion_Driver/driver/eMPL/inv_mpu.c \
Middlewares/MPU6050_Motion_Driver/driver/eMPL/inv_mpu_dmp_motion_driver.c \
Middlewares/MPU6050_Motion_Driver/driver/stm32L/log_stm32.c \
Middlewares/MPU6050_Motion_Driver/eMPL-hal/eMPL_outputs.c \
Middlewares/MPU6050_Motion_Driver/mllite/data_builder.c \
Middlewares/MPU6050_Motion_Driver/mllite/hal_outputs.c \
Middlewares/MPU6050_Motion_Driver/mllite/message_layer.c \
Middlewares/MPU6050_Motion_Driver/mllite/ml_math_func.c \
Middlewares/MPU6050_Motion_Driver/mllite/mlmath.c \
Middlewares/MPU6050_Motion_Driver/mllite/mpl.c \
Middlewares/MPU6050_Motion_Driver/mllite/results_holder.c \
Middlewares/MPU6050_Motion_Driver/mllite/start_manager.c \
Middlewares/MPU6050_Motion_Driver/mllite/storage_manager.c \
Middlewares/MPU6050_Motion_Driver/porting/STM32F4_porting.c \
Middlewares/MPU6050_Motion_Driver/porting/pidControl.c \
Middlewares/MPU6050_Motion_Driver/porting/mpu6050_init.c \
Middlewares/MPU6050_Motion_Driver/porting/mpu6050_SL.c \
Middlewares/FreeRTOS/event_groups.c \
Middlewares/FreeRTOS/list.c \
Middlewares/FreeRTOS/queue.c \
Middlewares/FreeRTOS/stream_buffer.c \
Middlewares/FreeRTOS/tasks.c \
Middlewares/FreeRTOS/timers.c \
Middlewares/FreeRTOS/croutine.c \
Middlewares/FreeRTOS/portable/GCC/ARM_CM4F/port.c \
Middlewares/FreeRTOS/portable/MemMang/heap_4.c





# Core/Src/sensor/mpu6050.c \

# ASM sources
ASM_SOURCES =  \
startup_stm32f411xe.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F411xE \
-DEMPL \
-DUSE_DMP \
-DMPU6050 \
-DREMOVE_LOGGING \
-DEMPL_TARGET_STM32F4 \
-DMPL_LOG_NDEBUG=0

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-ICore/Inc/common \
-ICore/Inc/driver \
-ICore/Inc/rx \
-I/Users/echo/Development/arm-gnu-toolchain/arm64-arm-none-eabi12/arm-none-eabi/include \
-IMiddlewares/MPU6050_Motion_Driver/eMPL-hal \
-IMiddlewares/MPU6050_Motion_Driver/mllite \
-IMiddlewares/MPU6050_Motion_Driver/mpl \
-IMiddlewares/MPU6050_Motion_Driver/porting \
-IMiddlewares/MPU6050_Motion_Driver/driver/eMPL \
-IMiddlewares/MPU6050_Motion_Driver/driver/include \
-IMiddlewares/MPU6050_Motion_Driver/driver/stm32L \
-IMiddlewares/FreeRTOS/include \
-IMiddlewares/FreeRTOS/portable/GCC/ARM_CM4F \
-IMiddlewares/FreeRTOS/MemMang \
-IMiddlewares/FreeRTOS

#-ICore/Inc/sensor \


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections -Wl,-u,_printf_float,-u,_scanf_float -fmessage-length=0

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F411CEUx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys -llibmplmpu
LIBDIR = -LMiddlewares/MPU6050_Motion_Driver/mpl
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
